# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 42a960b0cff4f8a0e6bb43c94cc8836a2b4e46779c45841e734715f323d73ab1ea7f0f2ec01fc59f273161a1c0ed9a43004a8ff8686f073081e94f98839eb6c7

test:
  secret_key_base: 32c9301fa6132d106b599a469f16412da3c5707684de50ef068abb9e4aae7d1815d7a0952bfd2822e27c78a55eb3a088adf879751d8bb8ae8d6430e2c7b7191e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
